In [29]:
import numpy as np
import pandas as pd

In [30]:
temp_df = pd.read_csv("/home/kathan/Kathan/Natural Language Processing/Materials/IMDB Dataset.csv")
df = temp_df.iloc[:10000]
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [31]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]

In [32]:
df.shape

(10000, 2)

In [33]:
df['review'][1]


'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [34]:
df['sentiment'].value_counts()


positive    5028
negative    4972
Name: sentiment, dtype: int64

In [35]:
df.isnull().sum()


review       0
sentiment    0
dtype: int64

In [36]:
df.duplicated().sum()


17

In [37]:
df.drop_duplicates(inplace=True)


2023-04-10 14:51:49,737 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/3617111529.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)



In [38]:
df.duplicated().sum()


0

In [39]:
# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [40]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [41]:
df['review'] = df['review'].apply(remove_tags)


2023-04-10 14:51:51,911 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/1164145055.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)



In [42]:
df


review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [43]:
df['review'] = df['review'].apply(lambda x:x.lower())


2023-04-10 14:51:52,818 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/3523187300.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())



In [44]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

2023-04-10 14:51:56,171 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))



In [45]:
df


review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [46]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [47]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [48]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [49]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [50]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [52]:
X_train.shape


(7986, 1)

# Applying BoW


In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
cv = CountVectorizer()


In [55]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [56]:
X_train_bow.shape


(7986, 48282)

In [57]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [58]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [59]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]])

In [60]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8542814221331998

In [61]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8367551326990486

In [62]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8387581372058087

# Using TfIdf

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [64]:
tfidf = TfidfVectorizer()


In [65]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [66]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)


0.8407611417125689

# Using Word2Vec

In [67]:
import numpy as np
import pandas as pd

In [68]:
temp_df = pd.read_csv("/home/kathan/Kathan/Natural Language Processing/Materials/IMDB Dataset.csv")
df = temp_df.iloc[:10000]
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [69]:
df.drop_duplicates(inplace=True)

2023-04-10 14:59:26,249 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)



In [70]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text


In [71]:
df['review'] = df['review'].apply(remove_tags)

2023-04-10 14:59:27,667 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)



In [72]:
df['review'] = df['review'].apply(lambda x:x.lower())


2023-04-10 14:59:28,208 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/3523187300.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())



In [73]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

2023-04-10 14:59:31,644 [9315] WARNING  py.warnings:109: [JupyterRequire] /tmp/ipykernel_9315/2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))



In [74]:
df['review']


0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...                        
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [75]:
import gensim
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [76]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [77]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [78]:
model.build_vocab(story)



In [79]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5876359, 6212140)

In [80]:
len(model.wv.index_to_key)

31845

In [81]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [82]:
document_vector(df['review'].values[0])

array([-0.16483827,  0.40979606,  0.17927925,  0.20664698, -0.11853424,
       -0.59622866,  0.1914826 ,  0.9390852 , -0.35213512, -0.28536898,
       -0.247309  , -0.42451587,  0.1184805 ,  0.14851485,  0.15079433,
       -0.08453013,  0.00185535, -0.30490252, -0.05534428, -0.7154157 ,
        0.01441749,  0.21678504,  0.07040572, -0.2533617 , -0.3222349 ,
       -0.05066266, -0.2457129 ,  0.02700247, -0.29331827,  0.06337515,
        0.33339098,  0.03927721,  0.19356829, -0.26743042, -0.15469028,
        0.3600785 ,  0.07468841, -0.365079  , -0.2125322 , -0.78699857,
        0.14842759, -0.22826406,  0.05044918, -0.11917447,  0.46232808,
       -0.1612659 , -0.21195614, -0.03124376,  0.07257181,  0.37978524,
        0.0924281 , -0.3453271 , -0.44211882, -0.16208237, -0.07612513,
        0.23175766,  0.19278203,  0.03942421, -0.3052658 ,  0.06111179,
        0.04900745,  0.06388578,  0.08906534, -0.1136551 , -0.42279497,
        0.27045095,  0.04362475,  0.14398842, -0.38766402,  0.30

In [83]:
from tqdm import tqdm


In [84]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|███████████████████████████████████████| 9983/9983 [06:55<00:00, 24.05it/s]


In [85]:
X = np.array(X)


In [86]:
X[0]


array([-0.16483827,  0.40979606,  0.17927925,  0.20664698, -0.11853424,
       -0.59622866,  0.1914826 ,  0.9390852 , -0.35213512, -0.28536898,
       -0.247309  , -0.42451587,  0.1184805 ,  0.14851485,  0.15079433,
       -0.08453013,  0.00185535, -0.30490252, -0.05534428, -0.7154157 ,
        0.01441749,  0.21678504,  0.07040572, -0.2533617 , -0.3222349 ,
       -0.05066266, -0.2457129 ,  0.02700247, -0.29331827,  0.06337515,
        0.33339098,  0.03927721,  0.19356829, -0.26743042, -0.15469028,
        0.3600785 ,  0.07468841, -0.365079  , -0.2125322 , -0.78699857,
        0.14842759, -0.22826406,  0.05044918, -0.11917447,  0.46232808,
       -0.1612659 , -0.21195614, -0.03124376,  0.07257181,  0.37978524,
        0.0924281 , -0.3453271 , -0.44211882, -0.16208237, -0.07612513,
        0.23175766,  0.19278203,  0.03942421, -0.3052658 ,  0.06111179,
        0.04900745,  0.06388578,  0.08906534, -0.1136551 , -0.42279497,
        0.27045095,  0.04362475,  0.14398842, -0.38766402,  0.30

In [87]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])


In [88]:
y


array([1, 1, 1, ..., 0, 0, 1])

In [89]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [90]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [91]:
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7776664997496244