In [5]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import cv2

In [4]:
path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/"
img_name = 'download.jpeg'

# Read The Image 

In [ ]:
img = cv2.imread(path + '//' + img_name)

cv2.imshow("image",img)

cv2.waitKey(0)

cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread (0x40042a0).
Cannot move to target thread (0x4881010)

QObject::moveToThread: Current thread (0x4881010) is not the object's thread

# Resize The Image

In [ ]:
img = cv2.imread(path + '//' + img_name)

img = cv2.resize(img,(600,400))

cv2.imshow("image",img)

cv2.waitKey(0)

cv2.destroyAllWindows()

# Read All Images

In [6]:
import os

In [7]:
img_names = os.listdir('Images')
img_names

['download (1).jpeg',
 'download (3).jpeg',
 'download (2).jpeg',
 'download.jpeg']

In [8]:
path = r"/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/"

for img_name in img_names:
    img_path_full = path + img_name
    img = cv2.imread(img_path_full)
    img = cv2.resize(img,(600,400))
    cv2.imshow("image",img)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Print Single Image 4 Times

In [9]:
import numpy as np


for img_name in img_names:
    img_path_full = path + img_name
    img = cv2.imread(img_path_full)
    img = cv2.resize(img,(300,200))
    img_2 = np.hstack((img,img))
    img_4 = np.vstack((img_2,img_2))
    cv2.imshow("4 image",img_4)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

In [10]:
import numpy as np          # 3*2


for img_name in img_names:
    img_path_full = path + img_name
    img = cv2.imread(img_path_full)
    img = cv2.resize(img,(300,200))
    img_2 = np.hstack((img,img,img))
    img_4 = np.vstack((img_2,img_2))
    cv2.imshow("4 image",img_4)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

In [11]:
import numpy as np          # 3*3


for img_name in img_names:
    img_path_full = path + img_name
    img = cv2.imread(img_path_full)
    img = cv2.resize(img,(300,200))
    img_2 = np.hstack((img,img,img))
    img_4 = np.vstack((img_2,img_2,img_2))
    cv2.imshow("4 image",img_4)
    cv2.waitKey(0)
    
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Play Video Using OpenCV

In [13]:
video_path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/sample-5s.mp4"

In [19]:
cap = cv2.VideoCapture(video_path) '(0)' # to access system camera we use 0 inplace of videopath 

while cap.isOpened():
    ret,frame = cap.read()
    if ret:
        image = cv2.resize(frame,(600,400))
        cv2.imshow('video player',image)
        
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Read Image using OpenCV

- Syntax: cv2.imread(path, flag)

- flag: default value is cv2.IMREAD_COLOR

### Parameters:

- cv2.IMREAD_COLOR or 1: reads the image with RGB colors

- cv2.IMREAD_GRAYSCALE or 0: reads the image with gray colors

- cv2.IMREAD_UNCHANGED or -1: It reads the image as is from the source. If the source image is an RGB, it loads the image into an array with Red, Green, and Blue channels. If the source image is ARGB, it loads the image with three color components along with the alpha or transparency channel.

In [20]:

path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/download.jpeg"


img = cv2.imread(path)

print(img)

[[[56 59 57]
  [56 59 57]
  [57 60 58]
  ...
  [22 22 22]
  [22 22 22]
  [22 22 22]]

 [[61 64 62]
  [62 65 63]
  [62 65 63]
  ...
  [22 22 22]
  [22 22 22]
  [22 22 22]]

 [[63 66 64]
  [64 67 65]
  [64 67 65]
  ...
  [22 22 22]
  [22 22 22]
  [22 22 22]]

 ...

 [[17 19 19]
  [17 19 19]
  [17 19 19]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[17 19 19]
  [17 19 19]
  [17 19 19]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]]


In [21]:
print(img.shape)

(177, 284, 3)


In [23]:
path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/download.jpeg"


img = cv2.imread(path,cv2.IMREAD_GRAYSCALE) 'Or we can Write img = cv2.imread(path,0)'

print(img)

cv2.imshow("image",img)

cv2.waitKey(0)

cv2.destroyAllWindows()

[[58 58 59 ... 22 22 22]
 [63 64 64 ... 22 22 22]
 [65 66 66 ... 22 22 22]
 ...
 [19 19 19 ...  2  2  2]
 [19 19 19 ...  2  2  2]
 [21 21 21 ...  2  2  2]]


QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Read Image in Alpha or Transference Format

In [24]:
path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/download.jpeg"

 
img = cv2.imread(path, -1) #read image alpha or transparency format
 
print(img.shape)#print shape of image
print(img) #print image array
 
cv2.imshow('image', img) #show image
cv2.waitKey(0) #wait to close image window
 
cv2.destroyAllWindows() #cloase all windows


(177, 284, 3)
[[[56 59 57]
  [56 59 57]
  [57 60 58]
  ...
  [22 22 22]
  [22 22 22]
  [22 22 22]]

 [[61 64 62]
  [62 65 63]
  [62 65 63]
  ...
  [22 22 22]
  [22 22 22]
  [22 22 22]]

 [[63 66 64]
  [64 67 65]
  [64 67 65]
  ...
  [22 22 22]
  [22 22 22]
  [22 22 22]]

 ...

 [[17 19 19]
  [17 19 19]
  [17 19 19]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[17 19 19]
  [17 19 19]
  [17 19 19]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]]


QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Everything About cv2.imshow()

## Syntax: cv2.imshow( windows_name, numpy_array)
- windows_name: string value
- numpy_array: 2d or 3d NumPy array

In [26]:
# Show Numpy array as Image

In [27]:
import cv2
import numpy as np
 
matx = np.zeros((200,200)) # numpy array with width =200, height=200
 
cv2.imshow("Zeros matx", matx) # show numpy array
 
cv2.waitKey(0) # wait for ay key to exit window
cv2.destroyAllWindows() # close all windows

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

In [28]:
# Show Image


img_path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/download.jpeg" # image name
img = cv2.imread(img_path) #  read image and store in numpy array
 
cv2.imshow("Model image", img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

In [31]:
# Show same image in multiple windows

# To show same image in multiple windows we need to use cv2.imshow() unction multiple time with unique windoes_name."



In [32]:
img_path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/download.jpeg" # image name
 
img = cv2.imread(img_path)
 
# Showing same image in 3 windows
cv2.imshow("Model image 1", img)
cv2.imshow("Model image 2 ", img)
cv2.imshow("Model image 3", img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Save Image

- OpenCV library has powerful function named as cv2.imwrite(). Which saves the NumPy array in the form of an Image.

- cv2.imwrite() function takes any size of NumPy array and saves it as an image in JPEG or PNG file format.

# How to save image or NumPy array as image

In [33]:
import cv2
import numpy as np
import os
 
rand_array = np.random.randint(255, size = (300,600,3))
 
cv2.imwrite("rand_np_array.png", rand_array) # imwrite(filename, img[, params])
 
img = cv2.imread("rand_np_array.png")
cv2.imshow('image', img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

## Save Image

In [34]:
img_path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/download.jpeg" # image name
 
img = cv2.imread(img_path)
cv2.imshow('image', img)
 
cv2.imwrite("model_write.png", img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

# Save Images from Video

In [35]:
import cv2
import numpy as np
import os
 
video_path = "/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/sample-5s.mp4" 
os.mkdir("video_to_image") # create directory
 
cap = cv2.VideoCapture(video_path) # capture video
 
img_count = 1
while cap.isOpened():
    ret, frame = cap.read() # read video frame
     
    if not ret:
        print("Unable to read frame")
        break
     
    is_img_write = cv2.imwrite(f"video_to_image\image{img_count}.jpeg", frame)
     
    if is_img_write:
        print(f'image save at video_to_image\image{img_count}.jpeg')
         
    cv2.imshow("video", frame )
     
    cv2.waitKey(25) & 0xff == ord('q')
    img_count += 1
     
cap.release()
cv2.destroyAllWindows()

image save at video_to_image\image1.jpeg
image save at video_to_image\image2.jpeg
image save at video_to_image\image3.jpeg


QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread (0x33ac580).
Cannot move to target thread (0x32a1350)

QObject::moveToThread: Current thread (0x32a1350) is not the object's thread

image save at video_to_image\image4.jpeg
image save at video_to_image\image5.jpeg
image save at video_to_image\image6.jpeg
image save at video_to_image\image7.jpeg
image save at video_to_image\image8.jpeg
image save at video_to_image\image9.jpeg
image save at video_to_image\image10.jpeg
image save at video_to_image\image11.jpeg
image save at video_to_image\image12.jpeg
image save at video_to_image\image13.jpeg
image save at video_to_image\image14.jpeg
image save at video_to_image\image15.jpeg
image save at video_to_image\image16.jpeg
image save at video_to_image\image17.jpeg
image save at video_to_image\image18.jpeg
image save at video_to_image\image19.jpeg
image save at video_to_image\image20.jpeg
image save at video_to_image\image21.jpeg
image save at video_to_image\image22.jpeg
image save at video_to_image\image23.jpeg
image save at video_to_image\image24.jpeg
image save at video_to_image\image25.jpeg
image save at video_to_image\image26.jpeg
image save at video_to_image\image27.jpe

# Video From NumPy Array

In [ ]:
import numpy as np
import cv2
import os
 
width = 1280
hieght = 720
channel = 3
 
fps = 30
sec = 5
 
# Syntax: VideoWriter_fourcc(c1, c2, c3, c4) # Concatenates 4 chars to a fourcc code
#  cv2.VideoWriter_fourcc('M','J','P','G') or cv2.VideoWriter_fourcc(*'MJPG)
 
fourcc = cv2.VideoWriter_fourcc(*'MP42') # FourCC is a 4-byte code used to specify the video codec.
# A video codec is software or hardware that compresses and decompresses digital video. 
# In the context of video compression, codec is a portmanteau of encoder and decoder, 
# while a device that only compresses is typically called an encoder, and one that only 
# decompresses is a decoder. Source - Wikipedia
 
#Syntax: cv2.VideoWriter( filename, fourcc, fps, frameSize )
video = cv2.VideoWriter('test.mp4', fourcc, float(fps), (width, hieght))
 
for frame_count in range(fps*sec):
    img = np.random.randint(0,255, (hieght, width, channel), dtype = np.uint8)
    video.write(img)
video.release()

# Video from Images

In [ ]:
import numpy as np
import cv2
import os
 
width = 1280
hieght = 720
channel = 3
 
fps = 10
sec = 5
 
fourcc = cv2.VideoWriter_fourcc(*'MP42')
 
video = cv2.VideoWriter('image_to_video.avi', fourcc, float(fps), (width, hieght))
 
directry = r'/home/kathan/Kathan/Computer Vision/Indian AI Production/Images/'
 
img_name_list = os.listdir(directry)
 
for frame_count in range(fps*sec):
    
    img_name = np.random.choice(img_name_list)
    img_path = os.path.join(directry, img_name)
    img = cv2.imread(img_path)
    img_resize = cv2.resize(img, (width, hieght))
     
    video.write(img_resize)
     
video.release()